### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by DiablosOffens** [mpunkenhofer/MorasDBConverter#2]
@mpunkenhofer 
Hallo,
das ist eigtl. kein Issue eher ein Versuch der Kontaktaufnahme. 🤞
ich hatte vor einiger Zeit den original Moras Sourcecode in C# umgeschrieben und hier auf GitHub das Repository [Moras.Net](https://github.com/DiablosOffens/Moras.Net) dafür erstellt.
Zusätzlich zu der Umwandlung in C#-Code hab ich auch gleich einige Bugs, die nur im Sourcecode gefixt werden konnten, behoben und auch eine Import-Funktion für die offizielle Item-DB hinzugefügt. (Menüpunkt Einstellungen->Online-Update->Broadsword-Itemdatenbank)
Das fertige Release kann von dieser [Website](https://diablosoffens.github.io/Moras.Net/) direkt installiert werden, weil es eine Click-Once-App ist.
Ich wollte das ganze irgendwann mal [hier auf PostCount](http://www.postcount.net/forum/showthread.php?214882-Moras-1-124-Fix&p=3501835#post3501835) posten, aber es scheint, dass dort die Registrierung deaktiviert wurde.
Falls dafür noch Interesse besteht, kannst Du es auch gerne bei PostCount oder an anderer Stelle erwähnen.

**Comment by mpunkenhofer** [comment]
@DiablosOffens 
Hi,
ich bin schon einmal auf über dein repo gestolpert (super Job!), aber habe im Moment kein Interesse an Daoc. Ich habe damals halt einfach schnell was zusammen gebastelt und wollt mir porten bzw. umschreiben nicht antun. Immer wieder toll, dass doch noch für so ein altes game die community einspringt und das game & eco system am Leben erhält, danke also auch dir für deinen teil dazu!

Ein Projekt, das ich im Sinn hatte, falls ich wieder spielen sollte (abhängig von Servern & Freunden) war eine Webversion von einem equipment planner ala Moras.

**Comment by DiablosOffens** [comment]
Danke für die Infos.
Damit kann das hier geschlossen werden.
